services:
  backend:
    image: rba-be:local
    container_name: rba-backend
    ports:
      - "${APP_PORT:-8082}:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      DB_URL: ${DB_URL:-jdbc:postgresql://postgres:5432/room-booking}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-hieu}
      REDIS_HOST: redis
      REDIS_PORT: 6379

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
    healthcheck:
      test:  ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
#      - postgres
#      - redis
#      - nginx
  networks:
    - rba-db-network
    - rba-redis-network
    - rba-be-network

  postgres:
    image: ${DB_IMAGE:-postgres:18}
    container_name: ${DB_CONTAINERNAME:-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_DB: room-booking
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hieu}
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - rba-db-network

#  nginx:
#    image: nginx:1.30.4-alpine
#    container_name: my-nginx
#    ports:
#      - "80:80"

  frontend:
    image: ${FE_IMAGE:-rba-fe:local}
    container_name: ${FE_CONTAINERNAME:-rba-fe}
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8082/api/v1}
    ports:
      - "80:80"
    networks:
      - rba-be-network

  redis:
    image: ${REDIS_IMAGE:-redis:latest}
    container_name: ${REDIS_CONTAINERNAME:-redis}
    restart: unless-stopped
    networks:
      - rba-redis-network
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5



#Docker Networks
networks:
  rba-db-network:
    name: rba-db-network
    driver: bridge
  rba-redis-network:
    name: rba-redis-network
    driver: bridge
  rba-be-network:
    name: rba-be-network
    driver: bridge

volumes:
  postgres-data:
