server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /rba/api/v1
app:
  frontend-url: ${FRONTEND_URL:http://localhost:8081}
  jwt:
    accesssecret: ${JWT_ACCESS_SECRET}
    refreshsecret: ${JWT_REFRESH_SECRET}
    access-token-expire-seconds: 600
    refresh-token-expire-seconds: 604800

  cookie:
    secure: true
    same-site: Lax
#  redis:
#    host: ${REDIS_HOST:redis}
#    port: ${REDIS_PORT:6379}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/room-booking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:hieu}

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update # validate
    show-sql: false

file:
  upload-dir: ${UPLOAD_DIR:/app/uploads}

logging:
  level:
    org.springframework.web: INFO