server:
  port: 8082
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    accesssecret: bmd1b2kgZGFuIGJhIGNvIGNheSBjYSBsZW0gc2ljdWxh
    refreshsecret: bmd1b2kgZGFuIG9uZyBjbyBjb24gY29uZyBraG9uZyBuZ3U=
    access-token-expire-seconds: 600
    refresh-token-expire-seconds: 604800

  cookie:
    secure: false
    same-site: Lax

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/room-booking
    username: postgres
    password: hieu
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieuahieua@gmail.com
    password: ngjq orda ehxy dbxi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
file:
  upload-dir: D:/upload-arb/
logging:
  level:
    org.springframework.web: DEBUG