name: Docker Image CI for GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        run:  |
          docker login ghcr.io --username hieuhieu112 --password ${{ secrets.GH_PACKAGE_TOKEN }}
          docker build . --tag ghcr.io/hieuhieu112/rba-be:latest
          docker push ghcr.io/hieuhieu112/rba-be:latest
