# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
#   release:
#     types: [created]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test and Package
        run: mvn -B package --file pom.xml
  docker:
    needs: test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGE_TOKEN }}

    - name: Build image
      run: |
        docker build \
          -t ghcr.io/hieuhieu112/rba-be:${{ github.sha }} \
          .
    - name: Push image
      run: |
        docker push ghcr.io/hieuhieu112/rba-be:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e
          
            cd /root/rba            
            
            NEW_IMAGE="ghcr.io/hieuhieu112/rba-be:${{ github.sha }}"
            LKG_FILE=".last-known-good"
  
            echo "======================================"
            echo "New image: $NEW_IMAGE"
            echo "======================================"
  
            # -----------------------------------------
            # 1. Đọc Last Known Good
            # -----------------------------------------
             if [ -s "$LKG_FILE" ]; then
              LAST_KNOWN_GOOD=$(cat "$LKG_FILE")
              echo "Last known good: $LAST_KNOWN_GOOD"
            else
            LAST_KNOWN_GOOD=""
            echo "No last known good version found."
            fi
  
            # -----------------------------------------
            # 2. Deploy version mới
            # -----------------------------------------
  
            sed -i "s|^BACKEND_IMAGE=.*|BACKEND_IMAGE=$NEW_IMAGE|" .env
          
            echo "Deploying $NEW_IMAGE..."
  
            docker-compose pull backend
            docker-compose up -d backend
  
            # -----------------------------------------
            # 3. Chờ health check
            # -----------------------------------------
  
            echo "Waiting for backend health..."
  
            HEALTHY=false
  
            for i in {1..30}; do
            
            STATUS=$(docker inspect rba-be \
            --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' \
            2>/dev/null || echo "not-found")
            
            echo "Health status: $STATUS"
            
            if [ "$STATUS" = "healthy" ]; then
            HEALTHY=true
            break
            fi
            
            if [ "$STATUS" = "unhealthy" ]; then
            break
            fi
            
            sleep 10
            done
  
            # -----------------------------------------
            # 4. Deploy thành công
            # -----------------------------------------
  
            if [ "$HEALTHY" = true ]; then
            
            echo "======================================"
            echo "Deployment successful!"
            echo "Version: $NEW_IMAGE"
            echo "======================================"
            
            echo "$NEW_IMAGE" > "$LKG_FILE"
            
            exit 0
            fi
  
            # -----------------------------------------
            # 5. Deploy thất bại
            # -----------------------------------------
  
            echo "======================================"
            echo "Deployment failed!"
            echo "======================================"
  
            # Không có version tốt để rollback
            if [ -z "$LAST_KNOWN_GOOD" ]; then
            echo "No last known good version available."
            echo "Rollback cannot be performed."
            
            exit 1
            fi
  
            # -----------------------------------------
            # 6. Rollback
            # -----------------------------------------
  
            echo "Rolling back to:"
            echo "$LAST_KNOWN_GOOD"
  
            sed -i "s|^BACKEND_IMAGE=.*|BACKEND_IMAGE=$LAST_KNOWN_GOOD|" .env
  
            docker-compose pull backend
            docker-compose up -d backend
  
            # -----------------------------------------
            # 7. Kiểm tra version rollback
            # -----------------------------------------
  
            echo "Waiting for rollback health..."
  
            ROLLBACK_HEALTHY=false
  
            for i in {1..12}; do
            
            STATUS=$(docker inspect rba-be \
            --format='{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' \
            2>/dev/null || echo "not-found")
            
            echo "Rollback health status: $STATUS"
            
            if [ "$STATUS" = "healthy" ]; then
            ROLLBACK_HEALTHY=true
            break
            fi
            
            sleep 10
            done
  
            if [ "$ROLLBACK_HEALTHY" = true ]; then
            echo "======================================"
            echo "Rollback successful!"
            echo "Running: $LAST_KNOWN_GOOD"
            echo "======================================"
            
            exit 1
            fi
  
            echo "======================================"
            echo "CRITICAL: Rollback also failed!"
            echo "Version: $LAST_KNOWN_GOOD"
            echo "======================================"
  
            exit 1
            
            
            
            sed -i "s|^BACKEND_IMAGE=.*|BACKEND_IMAGE=ghcr.io/hieuhieu112/rba-be:${{ github.sha }}|" .env
            docker-compose pull
            docker-compose up -d